<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html>
<head>
  <meta charset="utf-8">
  
  <link rel="stylesheet" href="menu.css" type="text/css">
</head>

<body>

<center>

<div id="naglowek">

  <ol id="menu">
    
		<li><a href="index.php">Home</a></li>
		
		
		<li class="dol"><a href="#">O nas</a>
			<ul>
				<li><a href="historia.php">Nasza historia</a></li>
				<li><a href="dania.php">Dania</a></li>
				<li><a href="zalozyciele.php">Założyciele</a></li>
				<li><a href="specjalnosci.php">Specjalności</a></li>
			</ul>
		</li>
		
		<li class="dol"><a href="#">Menu</a>
      <ul>
					  <li><a href="przystawki.php">Przystawki</a></li>
            <li><a href="zupy.php">Zupy</a></li>
            <li><a href="dania_glowne.php">Dania główne</a></li>
            <li><a href="salatki.php">Sałatki</a></li>
						<li><a href="desery.php">Desery</a></li>
						<li><a href="napoje.php">Napoje</a></li>
        
			</ul>
		</li>
		
		
		<li class="dol"><a href="#">Dowóz</a>
      <ul>
						<li><a href="zasady.php">Zasady</a></li>
						<li><a href="oplaty.php">Opłaty</a></li>
			</ul>
			
		<li><a href="kontakt.php">Kontakt</a></li>
		
		
  </ol>
	
	</div>
	</center>
	



</body>
</html>